logging:
  formatter: json
  level: debug

domain: "https://s.url/"

server:
  grpc:
    port: 11050
  web: 
    port: 11051

cache:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 1
